// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPI-0EJZ5i0sQV3_KswxGQwKdcY9m8qv0',
    appId: '1:793605618948:web:d00383fff38fcb4590e451',
    messagingSenderId: '793605618948',
    projectId: 'dulieu-4b5f7',
    authDomain: 'dulieu-4b5f7.firebaseapp.com',
    databaseURL: 'https://dulieu-4b5f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieu-4b5f7.firebasestorage.app',
    measurementId: 'G-2V4X0TXQ29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoZwX7gydCvdHcgInIoDV4G_LEaJHYvV8',
    appId: '1:793605618948:android:1ffb3f220269e10e90e451',
    messagingSenderId: '793605618948',
    projectId: 'dulieu-4b5f7',
    databaseURL: 'https://dulieu-4b5f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieu-4b5f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhwC9QIV_snjHtw7D9h7XfQsTaKpag_jU',
    appId: '1:793605618948:ios:23f5a4ab2e2050bc90e451',
    messagingSenderId: '793605618948',
    projectId: 'dulieu-4b5f7',
    databaseURL: 'https://dulieu-4b5f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieu-4b5f7.firebasestorage.app',
    iosBundleId: 'com.example.sieuthoitiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhwC9QIV_snjHtw7D9h7XfQsTaKpag_jU',
    appId: '1:793605618948:ios:23f5a4ab2e2050bc90e451',
    messagingSenderId: '793605618948',
    projectId: 'dulieu-4b5f7',
    databaseURL: 'https://dulieu-4b5f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieu-4b5f7.firebasestorage.app',
    iosBundleId: 'com.example.sieuthoitiet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPI-0EJZ5i0sQV3_KswxGQwKdcY9m8qv0',
    appId: '1:793605618948:web:3413ee7b10183f9490e451',
    messagingSenderId: '793605618948',
    projectId: 'dulieu-4b5f7',
    authDomain: 'dulieu-4b5f7.firebaseapp.com',
    databaseURL: 'https://dulieu-4b5f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieu-4b5f7.firebasestorage.app',
    measurementId: 'G-0ZYPY9Y3XB',
  );
}
